"""Agent that turns the topic summary into a polished newsletter."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from src.agents.base_agent import BaseAgent


class WriterAgent(BaseAgent):
    """Final pipeline stage: composes the daily newsletter."""

    async def _load_context(self, input_path: str) -> dict[str, Any]:
        print(f"📖 Loading summary from {input_path}")
        content = Path(input_path).read_text(encoding="utf-8")
        return {"summary": content}

    async def _process(self, context: dict[str, Any]) -> dict[str, Any]:
        print("✍️  Writing newsletter...")
        prompt = f"""You are writing a daily AI/ML newsletter.

Here is the summary of today's articles:

{context['summary']}

Write an engaging newsletter with:
1. A catchy introduction (2-3 sentences)
2. Main content organized by topic (keep the summaries, add light context)
3. A brief conclusion

Use a professional but friendly tone. Use emoji sparingly."""
        newsletter = self._call_llm(prompt)
        return {"newsletter": newsletter, "date": datetime.now().strftime("%Y-%m-%d")}

    async def _save_result(self, result: dict[str, Any], output_path: str) -> None:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            f.write(f"# AI/ML Daily Newsletter - {result['date']}\n\n")
            f.write(result["newsletter"])
            f.write("\n\n---\n\n")
            f.write("*Generated by the AI Upskill multi-agent pipeline.*\n")
        print(f"💾 Newsletter saved to {out}")
